# Generated by Django 4.2.11 on 2024-03-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '8U'), (2, '10U'), (3, '11U'), (4, '12U'), (5, '14U'), (6, '16U'), (7, '18U'), (8, 'Open')], null=True),
        ),
    ]
