# Generated by Django 4.2.11 on 2024-03-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['created_on']},
        ),
    ]
