# Generated by Django 4.2.11 on 2024-03-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_webuser_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webuser',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='webuser',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
